spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          # No filters applied here as this is the authentication endpoint

        - id: user-service-protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter
            # This filter should authenticate requests

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
